name: Deploy Flex Function App

on:
  push:
    branches:
      - main  # Veya kullandığın branch adını burada belirt

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: bauphonicgit  # Azure Function App ismi
          publish-profile: ${{ secrets.AZUREAPPSVC_PUBLISHPROFILE }}
          package: .
